config/routes.rb
Rails.application.routes.draw do
  resources :users
  resources :courses
  root to: 'pages#home'
  
  # RESTful Routes (generated by scaffold)

  # TODO: sessions routes (see /controllers/sessions_controller.rb)
  # login points to session controller - new method
  # logout points to session controller - destroy method
  # TODO: add/drop courses routes (see /controllers/registrations_controller.rb)

  post '/login', to: 'sessions#create'
  get '/login', to: 'sessions#new'
  delete '/logout', to: 'sessions#destroy'

  post '/add_course/:user_id/:course_id', to: 'registrations#add_course', as: 'add_course'
  delete '/drop_course/:user_id/:course_id', to: 'registrations#drop_course', as: 'drop_course'

end

app/models/user.rb
class User < ApplicationRecord
  has_many :registrations, dependent: :destroy## WHY?
  has_many :courses, through: :registrations
  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :pennkey, presence: true
  validates :password_hash, presence: true
  validates :pennkey, uniqueness: true
  # users.password_hash in the database is a :string
  include BCrypt

  def password
    @password ||= Password.new(password_hash)
  end

  def password=(new_password)
    @password = Password.create(new_password)
    self.password_hash = @password
  end

  def full_name
    "#{first_name} #{last_name}"
  end

  def self.students 
    User.where(is_instructor: false)
  end

  def self.instructors 
    User.where(is_instructor: true)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user, except: [:create, :new]
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :check_user, only: [:edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
    @instructors = User.instructors
    @students = User.students
  end

  # GET /users/1
  # GET /users/1.json
  def show 
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    @user.password = user_params[:password_hash]

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    @user.assign_attributes(user_params)
    @user.password = user_params[:password_hash]

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    reset_session
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:first_name, :last_name, :pennkey, :is_instructor, :password_hash)
    end

    def check_user
      redirect_to '/courses' unless current_user == @user
    end
end

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :first_name %>
    <%= form.text_field :first_name %>
  </div>

  <div class="field">
    <%= form.label :last_name %>
    <%= form.text_field :last_name %>
  </div>

  <div class="field">
    <%= form.label :pennkey %>
    <%= form.text_field :pennkey %>
  </div>

  <div class="field">
    <%= form.label :is_instructor %>
    <%= form.check_box :is_instructor %>
  </div>

  <div class="field">
    <%= form.label :password_hash %>
    <%= form.text_field :password_hash %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<%= link_to 'New User', new_user_path %>

<br>

<h5>Instructors</h5>

<br>

<table>
  <thead>
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th>Pennkey</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>

    <% @users.each do |user| %>
      <% if user.is_instructor %>
        <tr>
          <td><%= user.first_name %></td>
          <td><%= user.last_name %></td>
          <td><%= user.pennkey %></td>
          <td><%= link_to 'Show', user %></td>
        </tr>
      <% end %>
    <% end %>
  </tbody>
</table>

<br>



<br>

<h5>Students</h5>

<table>
  <thead>
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th>Pennkey</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <% if !user.is_instructor %>
        <tr>
          <td><%= user.first_name %></td>
          <td><%= user.last_name %></td>
          <td><%= user.pennkey %></td>
          <td><%= link_to 'Show', user %></td>
        </tr>
      <% end %>
    <% end %>
  </tbody>
</table>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.first_name %>
  <%= @user.last_name %>
</p>

<p>
  <strong>Pennkey:</strong>
  <%= @user.pennkey %>
</p>

<p>
  <strong>Status:</strong>
  <%= @user.is_instructor ? "Instructor" : "Student" %>
</p>



<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>

<h3>
<%= @user.is_instructor ? "Courses Teaching" : "Courses Taking" %>
</h3>

<%if !current_user.is_instructor%>
  <div class="card" style="width: 18rem;">
    <% @user.courses.each do |course| %>
      <div class="card" style="width: 18rem;">
      <div class="card-body">
        <h5 class="card-title"><%=course.full_code%></h5>
        <h6 class="card-subtitle mb-2 text-muted"><%=course.instructor.full_name%></h6>
        <p class="card-text"><%=h truncate(course.description, :length => 120) %></p>
        <%= link_to 'Show', course%> 
        <%= link_to drop_course_path(current_user.id, course.id), method: :delete do %>
          <button type="button" class="btn btn-outline-secondary">Drop</button>
        <%end%> 
      </div>
    </div>
  <%end%>
<%else%>
  <% @user.courses.each do |course| %>
    <div class="card" style="width: 18rem;">
      <div class="card-body">
        <%= link_to 'Show', course%> 
        <%= link_to 'Edit', edit_course_path(course)%> 
      </div>
    </div>
  <%end%>
<%end%>  