config/routes.rb
Rails.application.routes.draw do
  resources :users
  resources :courses
  root to: 'pages#home'
  
  # RESTful Routes (generated by scaffold)

  # TODO: sessions routes (see /controllers/sessions_controller.rb)
  # login points to session controller - new method
  # logout points to session controller - destroy method
  # TODO: add/drop courses routes (see /controllers/registrations_controller.rb)

  post '/login', to: 'sessions#create'
  get '/login', to: 'sessions#new'
  delete '/logout', to: 'sessions#destroy'

  post '/add_course/:user_id/:course_id', to: 'registrations#add_course', as: 'add_course'
  delete '/drop_course/:user_id/:course_id', to: 'registrations#drop_course', as: 'drop_course'

end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  before_action :authenticate_user
  before_action :set_course, only: [:show, :edit, :update, :destroy]
  before_action :check_edit_authorization, only: [:edit, :update, :destroy]
  before_action :check_new_authorization, only: [:new, :create]

  # GET /courses
  # GET /courses.json
  def index
    @courses = Course.all
  end

  # GET /courses/1
  # GET /courses/1.json
  def show 
  end

  # GET /courses/new
  def new  
    @course = Course.new
  end

  # GET /courses/1/edit
  def edit 
  end

  # POST /courses
  # POST /courses.json
  def create
    
    @course = Course.new(course_params)

    respond_to do |format|
      if @course.save
        @course.users << current_user
        format.html { redirect_to @course, notice: 'Course was successfully created.' }
        format.json { render :show, status: :created, location: @course }
      else
        format.html { render :new }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /courses/1
  # PATCH/PUT /courses/1.json
  def update   
    respond_to do |format|
      if @course.update(course_params)
        format.html { redirect_to @course, notice: 'Course was successfully updated.' }
        format.json { render :show, status: :ok, location: @course }
      else
        format.html { render :edit }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /courses/1
  # DELETE /courses/1.json
  def destroy
    authenticate_user
    @course.destroy
    respond_to do |format|
      format.html { redirect_to courses_url, notice: 'Course was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_course
      @course = Course.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def course_params
      params.require(:course).permit(:department_id, :code, :title, :description)
    end

    def check_edit_authorization
      redirect_to "/courses" unless current_user.is_instructor && @course.instructor.id == current_user.id
    end

    def check_new_authorization
      redirect_to "/courses" unless current_user.is_instructor
    end
end

app/views/courses/_form.html.erb
<%= form_with(model: course, local: true) do |form| %>
  <% if course.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(course.errors.count, "error") %> prohibited this course from being saved:</h2>

      <ul>
      <% course.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :department_id %>
    <%= form.collection_select :department_id, Department.all, :id, :name %>
  </div>

  <div class="field">
    <%= form.label :code %>
    <%= form.number_field :code %>
  </div>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/courses/edit.html.erb
<h1>Editing Course</h1>

<%= render 'form', course: @course %>

<%= link_to 'Show', @course %> |
<%= link_to 'Back', courses_path %>

app/views/courses/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Courses</h1>

<br>

<div>
  <% if current_user.is_instructor %>
    <div>
      <%= link_to 'New Course', new_course_path%>
    </div>
  <%end%>
</div>

  <%if !current_user.is_instructor %>
    <% @courses.each do |course| %>
      <div class="card" style="width: 18rem;">
      <div class="card-body">
        <h5 class="card-title"><%=course.full_code%></h5>
        <h6 class="card-subtitle mb-2 text-muted"><%=course.instructor%></h6>
        <p class="card-text"><%=h truncate(course.description, :length => 120) %></p>
        <%= link_to 'Show', course%> 
        <%= link_to add_course_path(current_user.id, course.id), method: :post do %> 
          <button type="button" class="btn btn-outline-secondary">Add Course</button>
        <%end%>
      </div>
      </div>
    <%end%>
  <%else%>
    <% @courses.each do |course| %>
      <div class="card" style="width: 18rem;">
      <div class="card-body">
        <h5 class="card-title"><%=course.full_code%></h5>
        <h6 class="card-subtitle mb-2 text-muted"><%=course.instructor.full_name%></h6>
        <p class="card-text"><%=h truncate(course.description, :length => 120) %></p>
        <%= link_to 'Show', course%> 
        <%= link_to 'Edit', edit_course_path(course)%> 
      </div>
      <br>
      </div>
    <%end%>
  <%end%>  

app/views/courses/new.html.erb
<h1>New Course</h1>

<%= render 'form', course: @course %>

<%= link_to 'Back', courses_path %>

app/views/courses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Department:</strong>
  <%= @course.department_id %>
</p>

<p>
  <strong>Code:</strong>
  <%= @course.code %>
</p>

<p>
  <strong>Title:</strong>
  <%= @course.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @course.description %>
</p>

<%= link_to 'Edit', edit_course_path(@course) %> |
<%= link_to 'Back', courses_path %>




<%= link_to 'New Course', new_course_path %>